[colors.bright]
black = "#5E5C64"
blue = "#4499F8"
cyan = "#43E6FF"
green = "#5CFF39"
magenta = "#FF4FFE"
red = "#FF7120"
white = "#ffffff"
yellow = "#FFF300"

[colors.normal]
black = "#000000"
blue = "#0057FF"
cyan = "#00B6D1"
green = "#1AFF84"
magenta = "#EE00CB"
red = "#FF0000"
white = "#e5e5e5"
yellow = "#FFC21D"

[colors.primary]
background = "#1B1919"
foreground = "#ffffff"

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 9.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
decorations = "none"
opacity = 0.8
