[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.75

[cursor]
thickness = 0.2

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 9.5
offset.x = 0
offset.y = 0

[font.normal]
family = "JetBrainsMonoNerd Font"
style = "Medium"

[colors.bright]
black = "#3C4048"
blue = "#0000FF"
cyan = "#00FFFF"
green = "#40FF40"
magenta = "#BD5EFF"
red = "#FF1E1E"
white = "#FFFFFF"
yellow = "#FFFF80"

[colors.normal]
black = "#16181A"
blue = "#5EA1FF"
cyan = "#9EF1FF"
green = "#00FF00"
magenta = "#BD5EFF"
red = "#FF3232"
white = "#FFFFFF"
yellow = "#F1FF5E"

[colors.primary]
background = "#111111"
foreground = "#EEEEEE"

[colors.selection]
background = "#264F78"
foreground = "#FFFFFF"
