[env]
TERM = "alacritty"

[window]
decorations = "none"
opacity     = 0.75

[cursor]
thickness = 0.2

[cursor.style]
blinking = "On"
shape    = "Underline"

[font]
size     = 9.5
offset.x = 0
offset.y = 0

[font.normal]
family = "JetBrainsMonoNerd Font"
style  = "Medium"

[font.bold]
family = "JetBrainsMonoNerd Font"
style  = "ExtraBold"

[colors.cursor]
text   = "#4D4D4C"
cursor = "#F5E0DC"

[colors.bright]
black   = "#3C4048"
red     = "#FF1E1E"
green   = "#40FF40"
yellow  = "#F1FF8E"
blue    = "#5EA1FF"
magenta = "#BD5EFF"
cyan    = "#00FFFF"
white   = "#FFFFFF"

[colors.normal]
black   = "#16181A"
red     = "#FF033E"
green   = "#40FF80"
yellow  = "#FFFF40"
blue    = "#3BA1FF"
magenta = "#BD5EFF"
cyan    = "#9EF1FF"
white   = "#F8F8F8"

[colors.primary]
background = "#11111b"
foreground = "#EEEEEE"

[colors.selection]
background = "#264F78"
foreground = "#FFFFFF"
