[env]
TERM = "alacritty"

[window]
decorations     = "none"
dynamic_padding = true
opacity         = 0.75

[cursor]
thickness = 0.2

[cursor.style]
blinking = "On"
shape    = "Beam"

[font]
size     = 9.5
offset.x = 0
offset.y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Light"

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "ExtraBold"

[colors.cursor]
text   = "#11111E"
cursor = "#F5E0DC"

[colors.primary]
background = "#11111E"
foreground = "#DBDBDB"
dim_foreground = "#7F849C"
bright_foreground = "#FFFFFF"

[colors.selection]
background = "#264F78"
foreground = "CellForeground"

# Dim colors
[colors.dim]
black   = '#1E1E1E'
red     = '#FF6E6E'
green   = '#40CC80'
yellow  = '#AAAA40'
blue    = '#3BA1DD'
magenta = '#CC1AAC'
cyan    = '#00ABAB'
white   = '#BABABA'

# Normal colors
[colors.normal]
black   = "#2C2C2C"
red     = "#FF4E4E"
green   = "#40EE80"
yellow  = "#CCCC40"
blue    = "#00A1FF"
magenta = "#EC4DEC"
cyan    = "#00CCCC"
white   = "#DEDEDE"

# Bright colors
[colors.bright]
black   = "#3C4048"
red     = "#FF1E1E"
green   = "#20FF20"
yellow  = "#FFFF40"
blue    = "#2EA1FF"
magenta = "#FF1FFF"
cyan    = "#00FFFF"
white   = "#FFFFFF"

[keyboard]
bindings = [
  { key = "R", mods = "Control|Shift", command = { program = "alacritty", args = ["msg", "config", "-r"] } },
  { key = "T", mods = "Control|Shift", command = { program = "alacritty", args = ["msg", "config", "window.opacity=1"] } },
]
