[env]
TERM = "alacritty"

[window]
decorations     = "none"
dynamic_padding = true
opacity         = 0.75

[cursor]
thickness = 0.2

[cursor.style]
blinking = "On"
shape    = "Underline"

[font]
size     = 9.5
offset.x = 0
offset.y = 0

[font.normal]
family = "BlexMonoNerdFont"
style  = "Regular"

[font.bold]
family = "BlexMonoNerdFont"
style  = "Bold"

[colors.cursor]
text   = "#4D4D4C"
cursor = "#F5E0DC"

[colors.primary]
background = "#11111B"
foreground = "#DBDBDB"

[colors.selection]
background = "#264F78"
foreground = "#FFFFFF"

# Dim colors
[colors.dim]
black   = '#232323'
red     = '#FF6E6E'
green   = '#40CC80'
yellow  = '#DDDD40'
blue    = '#3BA1DD'
magenta = '#FF1AFF'
cyan    = '#00BBBB'
white   = '#BABABA'

# Normal colors
[colors.normal]
black   = "#16181A"
red     = "#FF4E4E"
green   = "#40EE80"
yellow  = "#EEEE40"
blue    = "#2BA1EE"
magenta = "#FF1AFF"
cyan    = "#00DEDE"
white   = "#DEDEDE"

# Bright colors
[colors.bright]
black   = "#3C4048"
red     = "#FF1E1E"
green   = "#40FF40"
yellow  = "#FFFF40"
blue    = "#2EA1FF"
magenta = "#FF4DFF"
cyan    = "#00FFFF"
white   = "#FFFFFF"

[keyboard]
bindings = [
  { key = "R", mods = "Control|Shift", command = { program = "alacritty", args = ["msg", "config", "-r"] } },
  { key = "T", mods = "Control|Shift", command = { program = "alacritty", args = ["msg", "config", "window.opacity=1"] } }
]
