gui:
  scrollHeight: 8
  expandFocusedSidePanel: true
  timeFormat: "02 Jan 06 15:04 MST"
  theme:
    activeBorderColor:
      - "cyan"
      - bold
    inactiveBorderColor:
      - "#bdbdbd"
      - bold
    optionsTextColor:
      - "#3b7dff"
    selectedLineBgColor:
      - "#004aab"
    cherryPickedCommitBgColor:
      - reverse
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#efef00"
    defaultFgColor:
      - default
  showIcons: false
git:
  log:
    showGraph: when-maximised
    showWholeGraph: false
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
confirmOnQuit: true
quitOnTopLevelReturn: false
notARepository: quit
keybinding:
  universal:
    quit: <esc>
    quit-alt1: q
    return: <c-c>
