-- hl.env('GDK_SCALE', '2')
-- hl.env('ICON_THEME', 'Yaru-dark')
hl.env('GTK_THEME', 'Win11-round-Dark')
hl.env('GTK_APPLICATION_PREFER_DARK_THEME', '1')
hl.env('GTK_FONT_NAME', 'Roboto 10')
hl.env('XCURSOR_SIZE', '16')
hl.env('HYPRCURSOR_SIZE', '16')
hl.env('QT_CURSOR_SIZE', '16')
hl.env('HYPRCURSOR_THEME', 'catppuccin-mocha-dark-cursors')
hl.env('XCURSOR_THEME', 'catppuccin-mocha-dark-cursors')
hl.env('QT_CURSOR_THEME', 'catppuccin-mocha-dark-cursors')
hl.env('QT_QPA_PLATFORMTHEME', 'qt6ct')
hl.env('QT_QPA_PLATFORM', 'wayland')
hl.env('ELECTRON_OZONE_PLATFORM_HINT', 'wayland')
hl.env('GDK_BACKEND', 'wayland')
