hl.on('hyprland.start', function()
  hl.exec_cmd('nm-applet')
  hl.exec_cmd('waybar')
  hl.exec_cmd('hypridle')
  -- hl.exec_cmd('blueman-applet')
  hl.exec_cmd('swaybg -i ~/Pictures/_wallpaper.*')
  hl.exec_cmd('wl-paste --watch cliphist -max-items 256 store')
end)
