general {
  lock_cmd = pidof hyprlock || hyprlock                                   # avoid starting multiple hyprlock instances.
  before_sleep_cmd = loginctl lock-session                                # lock before suspend.
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # to avoid having to press a key twice to turn on the display.
}

listener {
  timeout = 120 # save and restore screen brightness level
  on-timeout = brightnessctl --save && brightnessctl set 5%
  on-resume = brightnessctl --restore || brightnessctl set 20%
}

listener {
  timeout = 120 # save and restore keybord backlight brightness level
  on-timeout = brightnessctl --device 'platform::kbd_backlight' --save && brightnessctl --device 'platform::kbd_backlight' set 0
  on-resume = brightnessctl --device 'platform::kbd_backlight' --restore || brightnessctl --device 'platform::kbd_backlight' set 1
}

listener {
  timeout = 150 # lock screen
  on-timeout = loginctl lock-session
}

listener {
  timeout = 180 # turn of screen
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
