font_size        9.5
# font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Light
# bold_font        family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-ExtraBold
font_family      family='BlexMono Nerd Font' postscript_name=BlexMonoNF-Light
bold_font        family='BlexMono Nerd Font' postscript_name=BlexMonoNF-Bold

disable_ligatures              always
undercurl_style                thin-sparse

detect_urls                    yes
url_color                      #FFFF40
url_style                      dotted

confirm_os_window_close        0
shell_integration              no-cursor

background_opacity             0.75
dynamic_background_opacity     yes

scrollback_lines               5000
scrollback_pager               nvim --cmd 'lua vim.env.NVIM_NO_LUALINE=1'
                                  \ -c 'call nvim_open_term(0, {})'
                                  \ -c 'nnoremap q ZQ | stopinsert | $'
                                  \ -c 'set nomodified showmode signcolumn=yes:1'
                                  \ -c 'set number relativenumber laststatus=0 showtabline=0' -

scrollbar_track_opacity        0
scrollbar_track_color          #393939
scrollbar_handle_color         #777777

cursor                         #F5E0DC
cursor_text_color              #11111E
cursor_underline_thickness     1.5
cursor_beam_thickness          1.5

cursor_trail                          0
cursor_trail_decay             0.1 0.25
cursor_trail_start_threshold          2

# Colors
background             #11111E
selection_background   #264F78
selection_foreground   none

# black
color0    #2C2C2C
color8    #3C4048

# red
color1    #FF4E4E
color9    #FF1E1E

# green
color2    #40EE80
color10   #20FF20

# yellow
color3    #CCCC40
color11   #FFFF40

# blue
color4    #00A1FF
color12   #2BA1EE

# magenta
color5    #EC4DEC
color13   #FF1FFF

# cyan
color6    #00CCCC
color14   #00FFFF

# white
color7    #DEDEDE
color15   #FFFFFF

clear_all_shortcuts  yes
kitty_mod            ctrl+shift

map kitty_mod+n new_os_window
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+i kitten unicode_input

map kitty_mod+equal change_font_size all +0.5
map kitty_mod+minus change_font_size all -0.5
map kitty_mod+0     change_font_size all    0

map kitty_mod+space show_scrollback
map kitty_mod+g show_last_command_output
map kitty_mod+j scroll_line_down smooth
map kitty_mod+k scroll_line_up smooth
map kitty_mod+d scroll_page_down
map kitty_mod+u scroll_page_up
map kitty_mod+[ scroll_to_prompt -1
map kitty_mod+] scroll_to_prompt  1

map kitty_mod+x kitty_shell
map kitty_mod+e show_kitty_env_vars
map kitty_mod+l disable_ligatures_in all cursor

map kitty_mod+, edit_config_file
map kitty_mod+t set_background_opacity 1.0
map kitty_mod+r combine : load_config_file : disable_ligatures_in all always

map kitty_mod+/ command_palette
map kitty_mod+o open_url_with_hints

